skill_create:
    type:     rest
    resource: AppBundle\Controller\Skills\CreateController
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
