parameters:
#    parameter_name: value

services:
    app.repository.skill:
        class: Infrastructure\ODM\Repository\SkillsRepository
        arguments: ['@doctrine.odm.mongodb.document_manager']
    app.use_case.add_skill:
        class: Domain\UseCase\AddSkill
        arguments: ['@app.repository.skill', '@slugify']
