Domain\Model\Resource:
    type: embeddedDocument
    fields:
        id:
            type: string
            id: true
            strategy: NONE
        url:
            type: string
        description:
            type: string
