Domain\Model\Skill:
    fields:
        id:
            type: string
            id: true
            strategy: NONE
        name:
            type: string
        slug:
            type: string
    embedMany:
        resources:
            targetDocument: Domain\Model\Resource
